<?xml version="1.0" encoding="UTF-8"?><testrun name="CidadeTest" project="Recibo" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="br.com.db1.db1start.recibo.cidade.CidadeTest" time="0.804">
    <testcase name="deveSalvarUmaNovaCidade" classname="br.com.db1.db1start.recibo.cidade.CidadeTest" time="0.804">
      <error>javax.persistence.PersistenceException: [PersistenceUnit: db1start] Unable to build Hibernate SessionFactory&#13;
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:967)&#13;
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)&#13;
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)&#13;
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)&#13;
	at br.com.db1.db1start.recibo.cidade.CidadeTest.deveSalvarUmaNovaCidade(CidadeTest.java:15)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
Caused by: org.hibernate.MappingException: Could not determine type for: br.com.db1.db1start.recibo.pessoa.Pessoa, at table: recibo, for columns: [org.hibernate.mapping.Column(emitente)]&#13;
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:455)&#13;
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:422)&#13;
	at org.hibernate.mapping.Property.isValid(Property.java:226)&#13;
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:597)&#13;
	at org.hibernate.mapping.RootClass.validate(RootClass.java:265)&#13;
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:329)&#13;
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)&#13;
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)&#13;
	... 27 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
